# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '*/1 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/checkout@master
        with:
          token: ${{ secrets.BAS_DATA_TOKEN }}
          ref: refs/heads/main
          repository: edwardez/bas-data
          path: bas-data

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: |
          cd bas-data
          npm ci
          npm install -g typescript
          npm install -g ts-node

      - name: Run npm
        run: |
          cd bas-data
          echo "ls ."
          npm run dev
          echo "ls ."

